### ISSUE TITLE
Please "git tag" your RAKU modules with it's versions

### ISSUE THREAD

**Issue by AntonOks** [sergot/datetime-parse#22]
Can you please "GIT TAG" your RAKU modules with it's version, similar and at the same time you maintain it's **_"version": "x.y.z"_** in your `META6.json` file?

I was told, this will happen "for free" going forward with mi6 anyhow, but for now it would be great if you spend those 2 seconds already now :)

"Tagging" is generally highly appreciated in regards to "reproducible builds" and here especially for the ["Rakudo Star" modules](https://github.com/rakudo/star/blob/master/etc/modules.txt)

THANK YOU!

**Comment by AntonOks** [comment]
@sergot @bduggan @patrickbkr - could someone please

**Comment by bduggan** [comment]
Hi @AntonOks -- sorry, not sure I follow -- is there a module that is missing a tag for a version?  (I generally do make tags that correspond to versions)

**Comment by AntonOks** [comment]
@bduggan

In the META6.json we have ["version": "0.9.3"](https://github.com/sergot/datetime-parse/blob/4ad4ea1df1b4c91ff1ab8f7aadf91685de6a6189/META6.json#L25) but there are [no (similar) "git tags" in this REPO here](https://github.com/sergot/datetime-parse/tags)

If you **have git tags in your locally cloned repo** outside GitHub.com, say your local computer, you may need to push them with `git push --tags`

If you **do not have** tags in your locally cloned repo, you can create one, which refers to the commit, in which @sergot changed the META6.json to the current "version" by running `git tag -a "0.9.3" 4ad4ea1 -m "Tag version 0.9.3` and then push this change to GitHub, see above!

Thanks for your help!

**Comment by bduggan** [comment]
I see, @AntonOks -- I have contributed to this repo in the form of pull requests, but as far as I know I don't have permission to push directly to this repository (code or tags) -- so I'm not sure that I am able to help here.

**Comment by sergot** [comment]
@AntonOks just pushed the tag. By the way, is this a requirement for something? I don't really follow Raku recently so I might have missed something.

**Comment by sergot** [comment]
@AntonOks also please let me know if I've done it correctly :)

**Comment by AntonOks** [comment]
> @AntonOks also please let me know if I've done it correctly :)

THANK_YOU!!!

**Comment by AntonOks** [comment]
THANK_YOU!


Wel, yes, Rakudo Star relays on GIT TAGs...

 

Gesendet: Dienstag, 17. Oktober 2023 um 13:03 Uhr
Von: "Filip Sergot" ***@***.***>
An: "sergot/datetime-parse" ***@***.***>
Cc: "Anton Oks" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [sergot/datetime-parse] Please "git tag" your RAKU modules with it's versions (Issue #22)


 

@AntonOks just pushed the tag. By the way, is this a requirement for something? I don't really follow Raku recently so I might have missed something.

**Comment by AntonOks** [comment]
> @AntonOks just pushed the tag. By the way, is this a requirement for something? I don't really follow Raku recently so I might have missed something.

Yes and no. The [Rakudo Star modules](https://github.com/rakudo/star#community-modules) always wanted developers to "pin" their suggested modules. 

As currently only "git based modules" are added to Star, see https://raw.githubusercontent.com/rakudo/star/master/etc/modules.txt and "pinning" in git language means "tagging", I try to encourage the developers to enroll "git tags" for the Raku modules they release...
